server:
  port: 9091
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka,http://peer2:1112/eureka
management:
  security:
    enabled: false
provide-hello:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true  #关闭Hystrix熔断功能，下边的超时时间就没有用了
        isolation:
          thread:
            timeoutInMilliseconds: 50000  #设置全局Hystrix超时时间
feign:
  hystrix:
    enabled: true  #false关闭Feign客户端的hystrix支持
  compression:    #hystrix 支持请求Gzip压缩，提高通讯效率,减少性能损耗
    request:
      enable: true
      mime-types: text/xml, application/xml, application/json
      min-request-size: 2048    #设置压缩条件
    response:
      enable: true

logging:
  level:
    com:
      anleafworld:
        springclouddemoeurekafeignconsumer:
          service:
            UserService: debug

