server:
  port: 9090
spring:
  application:
    name: consumer-hello
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka,http://peer2:1112/eureka
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true