server:
  port: 5555
spring:
  application:
    name: agi-gateway
zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:9091/
    api-c:
      path: /api-c/**
      url: provide-hello
    api-d:
      path: /api-d/**
      url: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:1111/eureka/