server:
  port: 8091
spring:
  server:
    MaxFileSize: 300MB
    MaxRequestSize: 300MB
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB
  application:
    name: provide-hello
  datasource:
    name: tuser
    url: jdbc:mysql://47.99.123.118:3306/db_demouse
    username: root
    password: Zcwl@0710
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#使用peer1  peer2作用服务器名必须要更改当前电脑host文件127.0.0.1 peer1  | 127.0.0.1  peer2 否则访问不了
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka,http://peer2:1112/eureka
account:
  name: 一沙一世界 一花一天堂
  description: 双手握无限  刹那是永恒
management:
  security:
    enabled: false
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 118.24.234.156:22122
  storagePort: 80
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
  - 118.24.234.156:22122
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.springcloud.springclouddemoclient.entity
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql