spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaofuping/springcloudconfig
          search-paths: /config-repo
          username: shaofuping
          password: 61117001work
server:
  port: 6666
security:
  user:
    password: 4551eb35-45fc-404d-b285-82e0de83eaa8
    name: user
encrypt:
  key: didispace
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka,http://peer2:1112/eureka
